
module.exports = [
    // {selector:'', input: '', error: ''},
    {selector:'@header', input: 'asdlfj78', error: 'The "Header" field should be between 9 and 19 characters long.'},
    {selector:'@header', input: '12345678912345678912', error: 'The "Header" field should be between 9 and 19 characters long.'},
    {selector:'@mke', input: '123', error: 'The "MKE" field can only include characters from the English Alphabet or special characters.'},
    {selector:'@mke', input: '1', error: 'The "MKE" field should be between 2 and 4 characters long.'},
    {selector:'@mke', input: '12345', error: 'The "MKE" field should be between 2 and 4 characters long.'},
    {selector:'@oai', input: '12345678', error: 'The "Originating Agency Identifier" field should be 9 characters long.'},
    {selector:'@oai', input: '1234567891', error: 'The "Originating Agency Identifier" field should be 9 characters long.'},
    {selector:'@name', input: 'ab', error: 'The "Name" field should be between 3 and 30 characters long.'},
    {selector:'@name', input: 'qwertyuiopasdfghjklzxcvbnmlkjhg', error: 'The "Name" field should be between 3 and 30 characters long.'},
    {selector:'@height', input: 'abc', error: 'The "Height" field can only include numeric characters.'},
    {selector:'@height', input: '12', error: 'The "Height" field should be 3 characters long.'},
    {selector:'@height', input: '1234', error: 'The "Height" field should be 3 characters long.'},
    {selector:'@weight', input: 'abc', error: 'The "Weight" field can only include numeric characters.'},
    {selector:'@weight', input: '0', error: 'The "Weight" field needs to have a value greater than 0.'},
    {selector:'@weight', input: '1234', error: 'The "Weight" field should be between 1 and 3 characters long.'},
    {selector:'@hair', input: '123', error: 'The "Hair" field can only include characters from the English Alphabet or special characters.'},
    {selector:'@hair', input: 'ab', error: 'The "Hair" field should be between 3 and 10 characters long.'},
    {selector:'@hair', input: 'qwertyuiopa', error: 'The "Hair" field should be between 3 and 10 characters long.'},
    {selector:'@offense', input: 'abcd', error: 'The "Offense" field should be between 5 and 15 characters long.'},
    {selector:'@offense', input: 'qwertyuiopasdfgh', error: 'The "Offense" field should be between 5 and 15 characters long.'},
    {selector:'@dow', input: '12311899', error: `The "Date of Warrant/Violation" field must be entered as a date, MM/DD/YYYY, no earlier than 01/01/1900 and no later than today's date.`},
    {selector:'@dow', input: '12311899', error: ''},
]